version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "wikidotrb"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
