# Target Ruby Version
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 70

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/ModuleLength:
  Max: 500

Metrics/PerceivedComplexity:
  Max: 25

Metrics/AbcSize:
  Max: 80

Metrics/BlockLength:
  Max: 200

Metrics/ParameterLists:
  Max: 25

Layout/LineLength:
  Max: 200

Metrics/CollectionLiteralLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
