name: Auto-merge Dependabot PRs
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto-merge Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --auto --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
