name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3
      working-directory: wikidotrb

    - name: Make config.yml
      run: |
        echo "test:" > wikidotrb/config.yml
        echo "  username: '${{ secrets.WIKIDOT_USERNAME }}'" >> wikidotrb/config.yml
        echo "  password: '${{ secrets.WIKIDOT_PASSWORD }}'" >> wikidotrb/config.yml
        echo "  site: '${{ secrets.WIKIDOT_SITE }}'" >> wikidotrb/config.yml
      shell: bash

    
    - name: Run the default task
      run: bundle exec rake
      working-directory: wikidotrb
