title: Wikidotrb Documentation
description: Ruby client library for Wikidot
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: just-the-docs
color_scheme: "light"
sass:
  style: compressed

# Theme settings
search_enabled: true
heading_anchors: true
aux_links:
  "Wikidotrb on GitHub":
    - "https://github.com/username/wikidotrb"

# Collections for API documentation
collections:
  api_docs:
    output: true
    permalink: /api/:path/

# Just the Docs settings
just_the_docs:
  collections:
    api_docs:
      name: API Documentation

# Documentation generation settings
api:
  rdoc_path: "/api/rdoc"
  yard_path: "/api/yard"
  rbs_path: "/api/rbs"

# Footer content
footer_content: "Copyright &copy; 2025 The Wikidotrb Authors."

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _scripts/
