source "https://rubygems.org"

gem "jekyll", "~> 4.2"
gem "just-the-docs", "~> 0.5"
gem "webrick", "~> 1.7"
gem "rake", "~> 13.0"

# Required for documentation processing
gem "fileutils", "~> 1.7"
gem "json", "~> 2.6"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.16"
  gem "jekyll-seo-tag", "~> 2.8"
end
